### ISSUE TITLE
import TimelineMax from 'gsap';

### ISSUE THREAD

**Issue by phsgoes** [kugatsu765/vueNotification#2]
Hi. I've decided to use your package in my project and certain things I cannot configure very well. Basically, what I'm trying to accomplish is to reduce animation time that is quite slow and then I followed your instructions. First, I imported TimelineMax from GSAP

`import TimelineMax from 'gsap';`

Then I start to configure the notification:

` this.$notification.success(message, {
        title: this.t('messages.SUCCESS'),
        timer: 5,
        animateIn: () => {
          let tl = new TimelineMax()
            .from(`.vn-notif${this.uuid}`, 0.6, {
              opacity: 0
            })
            .from(this.notificationEl, 0.4, {
              borderRadius: 100,
              width: 20,
              height: 20
            })
            .from(`.vn-notif${this.uuid}>div`, 0.3, {
              opacity: 0
            });
          tl.pause();
          return tl;
        }
      });`

And I've got an error in console: **Cannot tween a null target**. I tried to debug it with no success. What's actually happening in this case?

**Comment by kugatsu765** [comment]
Hello @phsgoes , sorry for the response time. 

I tried to reproduce your error and the problem comes from the arrow function. 
By doing this, you create a closure and your function runs in the parent context.  Replacing  `"() = > {} "` with  "`function () {}` " your notification should be displayed correctly.
